// Shared connection, authentication, CMS and data helpers for the existing app.
let sb=null,cfg=null,session=null,adminReady=false,authSubscription=null,recovery=false;
let viewVersion=0,toastTimer,authEpoch=0;
let cms={settings:null,services:[],faqs:[],areas:[],gallery:[]};
let jobRows=[],expenseRows=[],customerRows=[];
const app=document.getElementById('app'),toast=document.getElementById('toast');
const publicFacts={name:'RM Small Jobs',tagline:'Small jobs. Done properly.',phone:'07365 309553',email:'x7reecex@gmail.com',areas:'Motherwell, Wishaw and Bellshill'};
const sharedConfig=window.RM_CONFIG||{};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function say(v){clearTimeout(toastTimer);toast.textContent=v;toast.style.display='block';toastTimer=setTimeout(()=>toast.style.display='none',5000);}
function err(v){return `<div class="error">${esc(v)}</div>`;}
function field(id,label,value='',type='text',extra=''){return `<div class="field"><label for="${id}">${esc(label)}</label><input id="${id}" name="${id}" type="${type}" value="${esc(value)}" ${extra}></div>`;}
function textField(id,label,value='',extra=''){return `<div class="field"><label for="${id}">${esc(label)}</label><textarea id="${id}" name="${id}" rows="3" ${extra}>${esc(value)}</textarea></div>`;}
function value(id){return document.getElementById(id).value.trim();}
function pounds(v){if(v===null||v===undefined||v==='')return 'Not set';const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n):'Not set';}
function dateText(v){if(!v)return 'Not scheduled';const d=new Date(v);return Number.isNaN(d.getTime())?'Date unavailable':d.toLocaleString('en-GB',{timeZone:'Europe/London',dateStyle:'medium',timeStyle:'short'});}
function check(result,label){if(result.error)throw new Error(`${label}: ${result.error.message||'Request failed.'}`);return result.data;}
function checkSaved(result,label){const rows=check(result,label);if(!Array.isArray(rows)||rows.length!==1||rows[0]?.id==null)throw new Error(label+': the database did not confirm one saved record. Check the record list before retrying.');return rows[0];}
function newRequestId(){return crypto.randomUUID();}
function clearPrivate(){session=null;adminReady=false;recovery=false;authEpoch++;viewVersion++;cms={settings:null,services:[],faqs:[],areas:[],gallery:[]};jobRows=[];expenseRows=[];customerRows=[];}
function requireAuth(){if(!session||!adminReady)throw new Error('Please sign in with an approved business admin account.');}
function authCard(content){app.innerHTML=`<main class="auth"><div class="card"><img class="logo" src="logo.png" alt="RM Small Jobs">${content}</div><a class="inline-link" href="./">Back to public website</a></main>`;}
function validateConnection(url,key){
  const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||u.pathname!=='/'||u.search||u.hash)throw new Error('Use the HTTPS project URL from Supabase, with no extra path.');
  if(key.startsWith('sb_publishable_')&&key.length>20)return {url:u.origin,key};
  try{const part=key.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');const payload=JSON.parse(atob(part.padEnd(Math.ceil(part.length/4)*4,'=')));if(payload.role==='anon')return {url:u.origin,key};}catch{}
  throw new Error('Use only a Supabase publishable key or anon key. Secret keys, service-role keys and sign-in tokens cannot be used here.');
}
function setup(message=''){
  authCard(`<h1>Connect your business app</h1><p class="muted">Connect to the existing RM Small Jobs database.</p>${message?err(message):''}<form onsubmit="event.preventDefault();connect(this)">${field('url','Supabase project URL',cfg?.url||sharedConfig.supabaseUrl||'https://metquqdynxwkplojlhwq.supabase.co','url','required autocomplete="url"')}${textField('key','Publishable or anon key',cfg?.key||'','required autocomplete="off" spellcheck="false"')}<div class="form-error" role="alert"></div><button class="btn primary" type="submit">Connect</button></form><p class="muted">This public connection code is safe for a browser. Never enter a secret key, service-role key or password here. <a href="README.md">Setup instructions</a></p>`);
}
async function connect(form){await submit(form,async()=>{cfg=validateConnection(value('url'),value('key'));localStorage.setItem('rm_sb',JSON.stringify(cfg));await start();},false);}
async function resetConnection(){try{if(sb&&session)check(await sb.auth.signOut(),'Sign out');authSubscription?.unsubscribe();clearPrivate();localStorage.removeItem('rm_sb');sb=null;cfg=null;setup();}catch(e){say(e.message);}}
function connectionFailed(error){return /load failed|failed to fetch|networkerror|network request failed|fetch failed/i.test(error?.message||'');}
async function useWebsiteConnection(){
  if(session)return say('Sign out before changing the connection.');
  const resetEmail=document.getElementById('reset_email')?.value;
  try{
    const next=validateConnection(sharedConfig.supabaseUrl,sharedConfig.supabaseKey);
    authSubscription?.unsubscribe();clearPrivate();sb=null;cfg=next;
    localStorage.setItem('rm_sb',JSON.stringify(next));await start();
    if(resetEmail!==undefined&&document.getElementById('email')){showForgotPassword();document.getElementById('reset_email').value=resetEmail;}
  }catch(e){say(e.message);}
}
function login(message=''){
  clearPrivate();authCard(`<h1>Sign in</h1><p class="muted">Your private RM Small Jobs records.</p>${message?err(message):''}<form onsubmit="event.preventDefault();signin(this)">${field('email','Email','','email','required autocomplete="username"')}${field('pass','Password','','password','required autocomplete="current-password"')}<div class="form-error" role="alert"></div><div class="actions"><button class="btn primary" type="submit">Sign in</button><button class="btn secondary" type="button" onclick="showForgotPassword()">Forgot password?</button></div></form><button class="inline-link" type="button" onclick="resetConnection()">Change connection</button>`);
}
async function signin(form){await submit(form,async()=>{const data=check(await sb.auth.signInWithPassword({email:value('email'),password:document.getElementById('pass').value}),'Sign in');if(!data.session)throw new Error('No signed-in session was returned.');await enterSession(data.session);},false);}
async function enterSession(nextSession){
  session=nextSession;adminReady=false;const epoch=++authEpoch;
  let status;try{status=check(await sb.rpc('rm_admin_status'),'Check admin access');}catch(e){if(epoch===authEpoch)accessScreen('Database setup is needed',e.message+' Follow the database setup in the README, then try again.');return;}
  if(epoch!==authEpoch||!session)return;
  if(!status?.is_admin)return accessScreen('Admin access is not enabled','You are signed in, but this account has not been added as the business owner. Follow the owner access step in the setup instructions.');
  if(status.schema_version!==1)return accessScreen('Database update is needed','Run the current database setup before using these forms. Existing records have not been changed.');
  if(new URLSearchParams(location.search).get('change-password')==='1')return showPasswordReset();
  adminReady=true;shell();await home();
}
function accessScreen(title,message){adminReady=false;viewVersion++;authCard(`<h1>${esc(title)}</h1>${err(message)}<p class="muted">Your records have not been loaded.</p><div class="actions"><button class="btn primary" onclick="start()">Try again</button><button class="btn secondary" onclick="logout()">Log out</button><a class="btn secondary" href="README.md">Setup instructions</a><button class="btn secondary" onclick="downloadPublicConfig()">Download public connection file</button></div>`);}
function showForgotPassword(){const email=document.getElementById('email')?.value||'';authCard(`<h1>Reset your password</h1><p class="muted">Enter the email used for your business account.</p><form onsubmit="event.preventDefault();requestReset(this)">${field('reset_email','Account email',email,'email','required autocomplete="email"')}<div class="form-error" role="alert"></div><div class="actions"><button class="btn primary" type="submit">Email reset link</button><button class="btn secondary" type="button" onclick="login()">Back to sign in</button></div></form>`);}
async function requestReset(form){await submit(form,async()=>{check(await sb.auth.resetPasswordForEmail(value('reset_email'),{redirectTo:new URL('admin.html',location.href).href}),'Password reset');authCard('<h1>Check your email</h1><p>If that email has an account, a reset link has been requested. Open it on this device if possible.</p><button class="btn secondary" onclick="login()">Back to sign in</button>');},false);}
function showPasswordReset(){recovery=true;adminReady=false;viewVersion++;authCard(`<h1>Set a new password</h1><p class="muted">Choose a password of at least eight characters.</p><form onsubmit="event.preventDefault();changePassword(this)">${field('newpass','New password','','password','required minlength="8" autocomplete="new-password"')}${field('newpass2','Confirm password','','password','required minlength="8" autocomplete="new-password"')}<div class="form-error" role="alert"></div><button class="btn primary" type="submit">Save new password</button></form>`);}
async function changePassword(form){await submit(form,async()=>{if(!session)throw new Error('The reset link has expired. Request a new one.');const p=document.getElementById('newpass').value;if(p!==document.getElementById('newpass2').value)throw new Error('The passwords do not match.');check(await sb.auth.updateUser({password:p}),'Password update');recovery=false;history.replaceState(null,'',location.pathname);say('Password changed.');await enterSession(session);},false);}
async function start(){
  adminReady=false;viewVersion++;app.innerHTML='<main class="auth"><div class="card"><h1>Opening your business app…</h1><p class="muted" role="status">Checking your sign-in and access.</p></div></main>';
  try{
    let stored=null;try{stored=JSON.parse(localStorage.getItem('rm_sb')||'null');}catch{}
    const shared=sharedConfig.supabaseKey?{url:sharedConfig.supabaseUrl,key:sharedConfig.supabaseKey}:null;
    // Repair the old project-address typo without changing other saved projects.
    if(shared&&stored?.url?.replace(/\/$/,'')==='https://metaquqdynxwkplojlhwq.supabase.co'){stored=shared;localStorage.setItem('rm_sb',JSON.stringify(shared));}
    cfg=stored||shared;if(!cfg)return setup();cfg=validateConnection(cfg.url,cfg.key);
    if(!window.supabase?.createClient)return setup('The sign-in library did not load. Check your connection and refresh.');
    authSubscription?.unsubscribe();sb=window.supabase.createClient(cfg.url,cfg.key);
    authSubscription=sb.auth.onAuthStateChange((event,s)=>{
      if(event==='SIGNED_OUT'){clearPrivate();login();}
      else if(event==='PASSWORD_RECOVERY'&&s){session=s;showPasswordReset();}
      else if(s){if(session?.user?.id&&session.user.id!==s.user?.id){clearPrivate();}session=s;}
    }).data.subscription;
    const data=check(await sb.auth.getSession(),'Session check');session=data.session;
    const params=new URLSearchParams(location.hash.replace(/^#/,''));const search=new URLSearchParams(location.search);
    const recoveryError=params.get('error_description')||search.get('error_description');
    if(recoveryError){history.replaceState(null,'',location.pathname);return login('The sign-in or reset link could not be used: '+recoveryError);}
    if(recovery)return;if(!session)return login(search.get('change-password')==='1'?'This browser has no active sign-in. Open your newest password reset email link in this browser, or sign in first.':'');await enterSession(session);
  }catch(e){clearPrivate();setup(e.message);}
}
function shell(){requireAuth();app.innerHTML=`<header><div class="head"><div class="brand"><img class="logo" src="logo.png" alt="RM Small Jobs logo"><div><b>RM Small Jobs</b><small>Private business app</small></div></div><button class="btn secondary" onclick="logout()">Log out</button></div></header><nav class="nav" aria-label="Business app">${[['home','Home'],['jobs','Jobs'],['customers','Customers'],['money','Money'],['tools','More']].map(([id,name])=>`<button id="n-${id}" onclick="go('${id}')">${name}</button>`).join('')}</nav><main id="main"></main>`;}
function active(p){if(p==='website')p='tools';document.querySelectorAll('.nav button').forEach(x=>{const on=x.id==='n-'+p;x.classList.toggle('on',on);if(on)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');});}
function go(p){if(!session||!adminReady)return login();({home,jobs,customers,money,website,tools}[p]||home)();window.scrollTo(0,0);}
async function logout(){try{check(await sb.auth.signOut(),'Sign out');clearPrivate();login();}catch(e){say(e.message);}}
function loading(title,p){requireAuth();active(p);const token=++viewVersion;document.getElementById('main').innerHTML=`<h1>${esc(title)}</h1><div class="card" role="status">Loading your records…</div>`;return token;}
function current(token){return session&&adminReady&&token===viewVersion&&document.getElementById('main');}
function loadError(title,e,route,token){if(!current(token))return;document.getElementById('main').innerHTML=`<h1>${esc(title)}</h1><div role="alert">${err(e.message)}</div><button class="btn secondary" onclick="go('${route}')">Try again</button><p class="muted">Records could not be loaded. This does not mean they are empty. If a field is missing, finish the database setup in the README.</p>`;}
async function loadRows(table){requireAuth();const userId=session.user.id,rows=[];for(let offset=0;offset<100000;offset+=500){requireAuth();if(session.user.id!==userId)throw new Error('The signed-in account changed. Reload this page.');const page=check(await sb.from(table).select('*').order('id').range(offset,offset+499),'Load '+table)||[];requireAuth();if(session.user.id!==userId)throw new Error('The signed-in account changed.');rows.push(...page);if(page.length<500)return rows;}throw new Error('Too many records to load safely. No partial totals are shown.');}
async function saveEntity(table,id,data,requestId){
  requireAuth();const userId=session.user.id;
  const result=id!=null&&id!==''?await sb.from(table).update(data).eq('id',id).select('*'):await sb.from(table).insert({...data,client_request_id:requestId}).select('*');
  requireAuth();if(session.user.id!==userId)throw new Error('The signed-in account changed. Check the record list before retrying.');
  if(result.error?.code==='23505'&&!id){const existing=check(await sb.from(table).select('*').eq('client_request_id',requestId),'Check earlier save');if(existing?.length===1){const old=existing[0];const matches=Object.entries(data).every(([key,val])=>key==='scheduled_at'?(val===null?old[key]==null:Date.parse(old[key])===Date.parse(val)):['price','final_price','amount'].includes(key)?(val===null?old[key]==null:Number(old[key])===Number(val)):String(old[key]??'')===String(val??''));if(!matches)throw new Error('An earlier attempt saved this record with different details. Open it from the list before making further changes.');return old;}}
  return checkSaved(result,'Save '+table);
}
async function deleteEntity(table,id){requireAuth();return checkSaved(await sb.from(table).delete().eq('id',id).select('*'),'Delete '+table);}
async function submit(form,work,authenticated=true,validate=true){
  if(form.dataset.busy==='true'||(validate&&!form.reportValidity()))return;
  form.dataset.busy='true';const buttons=[...form.querySelectorAll('button')],box=form.querySelector('.form-error');box.innerHTML='';buttons.forEach(b=>b.disabled=true);
  try{if(authenticated)requireAuth();return await work();}catch(e){if(form.isConnected){
    if(!authenticated&&connectionFailed(e)){
      box.innerHTML=err('Could not reach the sign-in service. Check your internet connection and try again.')+'<p class="muted">If this page is open inside another app, open it in Safari or Chrome and retry.</p>'+(!session&&sharedConfig.supabaseKey?'<button class="btn secondary" type="button" onclick="useWebsiteConnection()">Use website connection</button>':'');
    }else box.innerHTML=err(e.message);
    box.scrollIntoView({block:'nearest'});
  }else say(e.message);}finally{form.dataset.busy='false';buttons.forEach(b=>b.disabled=false);}
}
function publicConnectionMatches(){return sharedConfig.supabaseUrl?.replace(/\/$/,'')===cfg?.url&&sharedConfig.supabaseKey===cfg?.key&&!!cfg?.key;}
function cmsNotice(){return publicConnectionMatches()?'Published content appears on the customer website when it is refreshed. Keep the homepage publication switch off until you have checked all the content.':'This device is connected, but the public website connection has not been configured to match it. Saves stay in the database until supabase-config.js is updated. Use the setup instructions before publishing.';}
async function website(tab='home'){
  const token=loading('Edit website','website');try{const data=await Promise.all(['site_settings','services','faqs','service_areas','gallery'].map(loadRows));if(!current(token))return;
    const settings=data[0].sort((a,b)=>String(a.id).localeCompare(String(b.id)));cms={settings:settings[0]||null,services:data[1],faqs:data[2],areas:data[3],gallery:data[4]};
    for(const k of ['services','faqs','areas'])cms[k].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)||String(a.id).localeCompare(String(b.id)));
    renderWeb(tab);
  }catch(e){loadError('Edit website',e,'website',token);}
}
function renderWeb(t='home'){requireAuth();document.getElementById('main').innerHTML=`<h1>Edit website</h1><div class="notice">${esc(cmsNotice())}</div><div class="actions"><a class="btn secondary" href="./" target="_blank" rel="noopener">View public site</a><button class="btn secondary" onclick="downloadPublicConfig()">Download connection file</button></div><div class="tabs subnav" aria-label="Website content">${[['home','Homepage'],['services','Services'],['faq','FAQs'],['areas','Areas'],['gallery','Gallery']].map(([id,label])=>`<button class="tab ${t===id?'on':''}" aria-pressed="${t===id}" onclick="renderWeb('${id}')">${label}</button>`).join('')}</div><div id="panel"></div>`;if(t==='home')homePanel();else collectionPanel(t);}
function homePanel(){const x=cms.settings||{};document.getElementById('panel').innerHTML=`<div class="card"><h2>Homepage and contact details</h2><form onsubmit="event.preventDefault();saveHome(this)">${field('headline','Headline',x.headline??publicFacts.tagline,'text','required maxlength="200"')}${textField('intro','Introduction',x.intro??'','maxlength="2000"')}${textField('boundary','Short price or scope note',x.boundary??'','maxlength="1000"')}${field('phone','Public phone number',x.phone??publicFacts.phone,'tel','autocomplete="tel"')}${field('whatsapp','WhatsApp number or wa.me link',x.whatsapp??'447365309553')}${field('public_email','Public email',x.email??publicFacts.email,'email','autocomplete="email"')}<label class="check"><input id="site_published" type="checkbox" ${x.published?'checked':''}>Publish the CMS content on the public website</label><p class="muted">When switched off, visitors see the built-in website. When switched on, enabled services, FAQs and areas and published gallery photos become public. Review every section first. Changing the WhatsApp number hides the old QR image until a matching QR is supplied.</p><div class="form-error" role="alert"></div><button class="btn primary" type="submit">Save homepage</button></form></div>`;}
function normalisePhone(text){let v=String(text||'').trim();if(!v)return '';if(v.startsWith('https://wa.me/')){const u=new URL(v);v=u.pathname.slice(1);if(u.hostname!=='wa.me')throw new Error('Use a phone number or wa.me link.');}v=v.replace(/[\s()\-]/g,'');if(v.startsWith('00'))v='+'+v.slice(2);if(/^0\d{9,10}$/.test(v))v='+44'+v.slice(1);if(/^44\d{9,10}$/.test(v))v='+'+v;if(!/^\+[1-9]\d{7,14}$/.test(v))throw new Error('Use a UK number or an international number starting with +.');return v;}
async function saveHome(form){await submit(form,async()=>{const d={headline:value('headline'),intro:value('intro'),boundary:value('boundary'),phone:value('phone'),whatsapp:value('whatsapp'),email:value('public_email'),published:document.getElementById('site_published').checked,updated_at:new Date().toISOString()};if(!d.headline)throw new Error('Enter a headline.');if(d.phone)normalisePhone(d.phone);if(d.whatsapp)d.whatsapp=normalisePhone(d.whatsapp).replace(/^\+/,'');if(d.published&&!cms.settings?.published&&!confirm('Publish the enabled website content? It can include the services, prices, FAQs, areas and gallery you have saved.'))return;checkSaved(cms.settings?await sb.from('site_settings').update(d).eq('id',cms.settings.id).select('id'):await sb.from('site_settings').insert(d).select('id'),'Save homepage');say(publicConnectionMatches()?'Homepage saved. Refresh the public site to check it.':'Homepage saved. Public connection setup is still needed.');if(form.isConnected)await website('home');});}
const collections={services:{table:'services',key:'services',title:'Services',fields:[['name','Service name'],['price','Starting price'],['description','Description','textarea']]},faq:{table:'faqs',key:'faqs',title:'FAQs',fields:[['question','Question'],['answer','Answer','textarea']]},areas:{table:'service_areas',key:'areas',title:'Service areas',fields:[['name','Area name']]},gallery:{table:'gallery',key:'gallery',title:'Gallery',fields:[['image_url','Photo URL','url'],['title','Photo title'],['description','Photo description','textarea']]}};
function collectionPanel(type){const c=collections[type],rows=cms[c.key];document.getElementById('panel').innerHTML=`<div class="card"><div class="actions"><h2>${c.title}</h2><button class="btn primary" onclick="recordForm('${type}',-1)">Add ${type==='gallery'?'photo':'item'}</button></div>${type==='gallery'?'<p class="muted">Use genuine work photos with permission. Use an HTTPS photo URL from your Supabase project or another image host listed in the connection file.</p>':''}${rows.length?rows.map((x,i)=>`<div class="row"><b>${esc(x.name||x.question||x.title||'Untitled item')}</b><p class="muted">${esc(x.price||x.answer||x.description||x.image_url||'')}</p><span class="badge">${(type==='gallery'?x.published:x.enabled)?'Visible when site published':'Hidden'}</span><div class="actions"><button class="btn secondary" onclick="recordForm('${type}',${i})">Edit</button></div></div>`).join(''):'<p class="empty">No items yet. Add one above.</p>'}</div>`;}
function recordForm(type,i){requireAuth();const c=collections[type],x=i<0?{}:cms[c.key][i];document.getElementById('panel').innerHTML=`<div class="card"><h2>${i<0?'Add':'Edit'} ${c.title.toLowerCase()}</h2><form data-record-index="${i}" onsubmit="event.preventDefault();saveRecord('${type}',${i},this)">${c.fields.map(([key,label,kind])=>kind==='textarea'?textField('record_'+key,label,x[key]??'',type==='faq'?'required maxlength="4000"':'maxlength="4000"'):field('record_'+key,label,x[key]??'',kind||'text','required maxlength="1000"')).join('')}${type!=='gallery'?field('record_order','Display order',x.sort_order??cms[c.key].length,'number','required min="0" max="10000" step="1"'):''}<label class="check"><input id="record_visible" type="checkbox" ${(type==='gallery'?x.published:x.enabled)?'checked':''}>Show on the published website</label><div class="form-error" role="alert"></div><div class="actions"><button class="btn primary" type="submit">Save item</button><button class="btn secondary" type="button" onclick="renderWeb('${type}')">Cancel</button></div></form></div>`;}
function validGalleryURL(text){const u=new URL(text);const hosts=[new URL(cfg.url).hostname,...(sharedConfig.galleryImageHosts||[])];if(u.protocol!=='https:'||u.username||u.password||!hosts.includes(u.hostname))throw new Error('Use an HTTPS photo on your Supabase project or an image host listed in supabase-config.js.');return u.href;}
async function saveRecord(type,i,form){await submit(form,async()=>{const c=collections[type],d={};for(const [key] of c.fields)d[key]=value('record_'+key);const required=type==='faq'?['question','answer']:type==='gallery'?['title','image_url']:type==='services'?['name','price']:['name'];if(required.some(key=>!d[key]))throw new Error('Fill in the required fields.');if(type==='gallery'){d.image_url=validGalleryURL(d.image_url);d.published=document.getElementById('record_visible').checked;}else{d.enabled=document.getElementById('record_visible').checked;d.sort_order=Number(value('record_order'));if(!Number.isInteger(d.sort_order)||d.sort_order<0)throw new Error('Use a whole number for display order.');}if(type==='services'){d.updated_at=new Date().toISOString();if(i<0)d.featured=false;}checkSaved(i<0?await sb.from(c.table).insert(d).select('id'):await sb.from(c.table).update(d).eq('id',cms[c.key][i].id).select('id'),'Save '+c.title);say('Website content saved.');if(form.isConnected)await website(type);});}
function downloadPublicConfig(){try{const safe=validateConnection(cfg.url,cfg.key);downloadJSON('supabase-config.js','window.RM_CONFIG = '+JSON.stringify({supabaseUrl:safe.url,supabaseKey:safe.key,galleryImageHosts:sharedConfig.galleryImageHosts||[]},null,2)+';\n','text/javascript');say('Public connection file downloaded. Follow the README to add it to the website.');}catch(e){say(e.message);}}
function downloadJSON(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportData(button){const box=document.getElementById('exportError');if(box)box.innerHTML='';button.disabled=true;try{requireAuth();const data={};for(const table of ['site_settings','services','faqs','service_areas','gallery','jobs','customers','expenses'])data[table]=await loadRows(table);requireAuth();const stamp=new Date().toISOString();downloadJSON('rm-small-jobs-private-backup-'+stamp.slice(0,10)+'.json',JSON.stringify({business:publicFacts.name,exported_at:stamp,format_version:2,tables:data},null,2));say('Private records exported. Keep this file somewhere private.');}catch(e){if(box?.isConnected)box.innerHTML=err(e.message);else say(e.message);}finally{button.disabled=false;}}
