// Private acquisition board. Saves records only; never posts or contacts anyone.
let leadRows=[];
const leadStages=['New opportunity','Contacted','Quote sent','Booked','Completed','Closed'];
const leadRelevance=['Needs checking','Request verified','Still needed confirmed','Closed or unsuitable'];
function safeLeadURL(raw){if(!raw)return '';const url=new URL(raw);if(url.protocol!=='https:'||url.username||url.password)throw new Error('Use a public HTTPS source link.');return url.href;}
function leadStage(row){const job=jobRows.find(x=>String(x.id)===String(row.job_id));if(!job)return row.status;if(statusIs(job,'Completed'))return 'Completed';if(statusIs(job,'Cancelled'))return 'Closed';if(statusIs(job,'Booked')||statusIs(job,'In progress'))return 'Booked';return row.status;}
function leadDue(row){return row.follow_up_on&&row.follow_up_on<=todayLondon()&&!['Completed','Closed'].includes(leadStage(row));}
function leadTotals(rows){
  let receipts=0;const paying=new Set();
  for(const row of rows){const paid=storedPennies(row.received_amount);if(paid===null)throw new Error('A lead has an invalid payment amount. Check it before relying on totals.');receipts+=paid;if(paid>0&&leadStage(row)==='Completed'&&row.customer_ref?.trim())paying.add(row.customer_ref.trim().toLowerCase());}
  return {receipts,paying:paying.size,booked:jobRows.filter(x=>statusIs(x,'Booked')||statusIs(x,'In progress')).length+rows.filter(x=>!x.job_id&&leadStage(x)==='Booked').length,completed:jobRows.filter(x=>statusIs(x,'Completed')).length+rows.filter(x=>!x.job_id&&leadStage(x)==='Completed').length};
}
async function leads(){const token=loading('Leads','tools');try{const [l,j]=await Promise.all([loadRows('leads'),loadRows('jobs')]);if(!current(token))return;leadRows=l;jobRows=j;renderLeads();}catch(e){if(current(token))document.getElementById('main').innerHTML=`<h1>Leads</h1><div role="alert">${err(e.message)}</div><p class="muted">If lead setup has not been approved and installed, complete supabase/04_lead_tracker.sql first. A failed load does not mean you have no leads.</p><button class="btn secondary" onclick="leads()">Try again</button>`;}}
function renderLeads(filter='all'){
 requireAuth();const totals=leadTotals(leadRows),rows=leadRows.filter(x=>filter==='all'||(filter==='due'?leadDue(x):leadStage(x)===filter)).sort((a,b)=>Number(!!leadDue(b))-Number(!!leadDue(a))||a.priority.localeCompare(b.priority));
 const counts=['New opportunity','Contacted','Quote sent'].map(stage=>[stage,leadRows.filter(x=>leadStage(x)===stage).length]);counts.push(['Follow-ups due',leadRows.filter(leadDue).length],['Booked jobs',totals.booked],['Completed jobs',totals.completed],['Payments recorded',pounds(totals.receipts/100)],['Completed paying customers',totals.paying+' / 5']);
 document.getElementById('main').innerHTML=`<h1>Win your first five customers</h1><p class="muted">Track real requests, your next action and money actually received. A public request is not a booking.</p><div class="grid">${counts.map(([label,n])=>`<div class="stat">${esc(label)}<b>${esc(n)}</b></div>`).join('')}</div><p class="muted">Payments are cumulative amounts manually recorded on leads, not quotes or job final prices. Use the same customer reference for repeat jobs. Linked jobs are counted once; existing jobs without a lead are included in booked/completed totals.</p><div class="actions"><button class="btn primary" onclick="newLead()">New opportunity</button><button class="btn secondary" onclick="exportLeads(this)">Export leads privately</button></div><div class="field"><label for="lead_filter">Show opportunities</label><select id="lead_filter" onchange="renderLeads(this.value)">${[['all','All'],['due','Follow-ups due'],...leadStages.map(s=>[s,s])].map(([v,n])=>`<option value="${esc(v)}" ${filter===v?'selected':''}>${esc(n)}</option>`).join('')}</select></div><div class="card">${rows.length?rows.map(row=>{let url='';try{url=safeLeadURL(row.source_url);}catch{}return `<div class="row"><b>${esc(row.title)}</b><p><span class="badge">${esc(row.priority+' · '+leadStage(row))}</span> ${leadDue(row)?'<span class="badge">Follow-up due</span>':''}</p><p class="muted">${esc(row.location||'Location needs checking')} · ${esc(row.relevance)}<br>Request date: ${esc(row.request_date_label||'Unknown; check the original post')}${row.follow_up_on?`<br>Follow-up: ${esc(plainDate(row.follow_up_on))}`:''}</p><div class="actions"><button class="btn secondary" data-id="${esc(row.id)}" onclick="newLead(this.dataset.id)">Open opportunity</button>${url?`<a class="btn secondary" href="${esc(url)}" target="_blank" rel="noopener noreferrer">View source</a>`:''}</div></div>`}).join(''):'<p class="empty">No opportunities in this view. Save genuine requests you can realistically help with.</p>'}</div>`;
}
function leadSelect(id,label,options,selected){return `<div class="field"><label for="${id}">${esc(label)}</label><select id="${id}">${options.map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(x)}</option>`).join('')}</select></div>`;}
function newLead(id=null){
 requireAuth();viewVersion++;const x=id?recordById(leadRows,id,'Opportunity'):{};
 document.getElementById('main').innerHTML=`<h1>${id?'Edit opportunity':'New opportunity'}</h1><div class="card"><form data-id="${esc(id||'')}" data-request-id="${esc(newRequestId())}" onsubmit="event.preventDefault();saveLead(this)">${field('lead_title','Work needed',x.title||'','text','required maxlength="200"')}${field('lead_location','Town / postcode',x.location||'','text','maxlength="500"')}${field('lead_source','Public source link',x.source_url||'','url','maxlength="2048"')}${field('lead_date','Request date as shown',x.request_date_label||'','text','maxlength="200"')}${leadSelect('lead_relevance','Is it still relevant?',leadRelevance,x.relevance||'Needs checking')}${leadSelect('lead_priority','Priority',['P1','P2','P3'],x.priority||'P2')}${leadSelect('lead_status','Stage',leadStages,x.status||'New opportunity')}${field('lead_followup','Follow-up date',x.follow_up_on||'','date','min="2000-01-01" max="2100-12-31"')}${field('lead_customer','Customer reference',x.customer_ref||'','text','maxlength="200"')}<p class="muted">Use a consistent private reference for the same person. Required when recording a payment; names alone can be ambiguous.</p>${field('lead_quote','Quote (£, optional)',x.quoted_price??'','number','min="0" max="1000000" step="0.01"')}${field('lead_received','Total payment received (£)',x.received_amount??0,'number','required min="0" max="1000000" step="0.01"')}<div class="field"><label for="lead_job">Link existing job (optional)</label><select id="lead_job"><option value="">No linked job</option>${jobRows.map(j=>`<option value="${esc(j.id)}" ${String(j.id)===String(x.job_id)?'selected':''}>${esc(j.title+' · '+j.status)}</option>`).join('')}</select></div><p class="muted">Create the job in Jobs when agreed, then link it here. Booked/completed/cancelled job status takes precedence. Linking does not copy prices or record payment.</p><label class="check"><input id="lead_offer" type="checkbox" ${x.offer_used?'checked':''}>Launch offer agreed for this customer</label>${textField('lead_response','Suggested response (draft only)',x.response_draft||'','maxlength="6000"')}${textField('lead_notes','Scope, travel and contact notes',x.notes||'','maxlength="6000"')}<p class="muted">Saving does not send messages. Check the original request, permissions, travel and tools before responding.</p><div class="form-error" role="alert"></div><div class="actions"><button class="btn primary" type="submit">Save opportunity</button><button class="btn secondary" type="button" onclick="renderLeads()">Back to leads</button></div></form></div>`;window.scrollTo(0,0);
}
async function saveLead(form){await submit(form,async()=>{
 const quote=moneyPennies(value('lead_quote'),'Quote'),received=moneyPennies(value('lead_received'),'Payment received',true),customer=value('lead_customer'),title=value('lead_title'),job=value('lead_job');
 if(!title)throw new Error('Enter what work is needed.');if(received>0&&!customer)throw new Error('Enter a consistent customer reference for this payment.');if(job&&!jobRows.some(x=>String(x.id)===job))throw new Error('Choose a current job.');
 const data={title,location:value('lead_location'),source_url:safeLeadURL(value('lead_source')),request_date_label:value('lead_date'),relevance:value('lead_relevance'),priority:value('lead_priority'),status:value('lead_status'),follow_up_on:value('lead_followup')||null,customer_ref:customer,quoted_price:quote===null?null:quote/100,received_amount:received/100,job_id:job||null,offer_used:document.getElementById('lead_offer').checked,response_draft:value('lead_response'),notes:value('lead_notes')};
 if(!leadStages.includes(data.status)||!leadRelevance.includes(data.relevance)||!['P1','P2','P3'].includes(data.priority))throw new Error('Choose valid stage, relevance and priority.');
 await saveEntity('leads',form.dataset.id||null,data,form.dataset.requestId);if(form.isConnected){say('Opportunity saved. No message sent.');await leads();}
 });}
async function exportLeads(button){button.disabled=true;try{const rows=await loadRows('leads');requireAuth();downloadJSON('rm-small-jobs-private-leads-'+todayLondon()+'.json',JSON.stringify({exported_at:new Date().toISOString(),leads:rows},null,2));say('Private lead export downloaded.');}catch(e){say(e.message);}finally{button.disabled=false;}}
