// Existing quote, reply and checklist tools.
function tools(tab='quote'){requireAuth();viewVersion++;active('tools');document.getElementById('main').innerHTML=`<h1>Tools for the next job</h1><p class="muted">Plan a sensible quote, prepare a reply and check you are ready to go.</p><div class="actions tools-links"><button class="btn primary" onclick="leads()">Leads & follow-ups</button><a class="btn secondary" href="admin.html?change-password=1">Change password</a><button class="btn primary" onclick="website()">Edit website</button><button class="btn secondary" onclick="downloadPublicConfig()">Public connection file</button></div><div class="tabs" aria-label="Business tools">${[['quote','Quote calculator'],['reply','Reply drafts'],['checklist','Job checklist']].map(([id,label])=>`<button class="tab ${id===tab?'on':''}" aria-pressed="${id===tab}" onclick="tools('${id}')">${label}</button>`).join('')}</div><div id="toolPanel"></div>`;if(tab==='reply')replyTool();else if(tab==='checklist')checklistTool();else quoteTool();}
function quoteTool(){document.getElementById('toolPanel').innerHTML=`<div class="split"><div class="card"><h2>Work out a quote</h2><form onsubmit="event.preventDefault();calculateQuote(this)"><div class="field"><label for="quote_service">Type of job</label><select id="quote_service"><option value="45">TV mounting — from £45</option><option value="30">Shelves, mirrors or wall hanging — from £30</option><option value="30">Furniture assembly — from £30</option><option value="30">Small household job — from £30</option><option value="35">Light garden tidy-up — from £35</option></select></div>${field('quote_hours','Total hours, including travel',1,'number','required min="0.25" max="1000" step="0.25" inputmode="decimal"')}${field('quote_rate','Your target pay per hour (£)','','number','required min="0.01" max="10000" step="0.01" inputmode="decimal"')}${field('quote_materials','Materials cost (£)',0,'number','required min="0" max="1000000" step="0.01" inputmode="decimal"')}${field('quote_travel','Travel cost (£)',0,'number','required min="0" max="1000000" step="0.01" inputmode="decimal"')}${field('quote_other','Other job costs (£)',0,'number','required min="0" max="1000000" step="0.01" inputmode="decimal"')}${field('quote_discount','Confirmed discount (£)',0,'number','required min="0" max="1000000" step="0.01" inputmode="decimal"')}<p class="muted">Only enter a discount if you have checked it applies. This calculator does not confirm launch-offer availability.</p><div class="form-error" role="alert"></div><button class="btn primary" type="submit">Work out quote</button></form></div><div class="card"><h2>Your estimate</h2><div id="quoteResult" aria-live="polite"><p class="muted">Include preparation and travelling time as well as time doing the job.</p></div><p class="muted">Estimates are rounded up to £5 before any discount. This is a planning guide, before tax and ongoing business costs. Check the actual job before agreeing a fixed price. Nothing is booked or saved here.</p></div></div>`;}
function calculateQuote(form){
  if(!form.reportValidity())return;
  const ids=['quote_service','quote_hours','quote_rate','quote_materials','quote_travel','quote_other','quote_discount'],[floor,hours,rate,materials,travel,other,discount]=ids.map(id=>Number(value(id))),errorBox=form.querySelector('.form-error');
  errorBox.innerHTML='';
  if(![floor,hours,rate,materials,travel,other,discount].every(Number.isFinite)||hours<=0||rate<=0||Math.min(materials,travel,other,discount)<0){errorBox.innerHTML=err('Check the hours, pay and costs.');return;}
  // Valid inputs use pennies and quarter-hours. Keep the target in quarter-pennies
  // so an exact £5 boundary cannot round up again through floating-point error.
  const [ratePennies,materialsPennies,travelPennies,otherPennies,discountPennies]=[rate,materials,travel,other,discount].map(n=>Math.round(n*100));
  const costPennies=materialsPennies+travelPennies+otherPennies,targetQuarterPennies=costPennies*4+Math.round(hours*4)*ratePennies,floorQuarterPennies=Math.round(floor*400),beforePennies=Math.ceil(Math.max(floorQuarterPennies,targetQuarterPennies)/2000)*500,result=document.getElementById('quoteResult');
  if(discountPennies>beforePennies){errorBox.innerHTML=err('Discount cannot exceed the quote before discount. Reduce the discount and calculate again.');result.innerHTML='<p class="muted">Adjust the discount to calculate a valid quote.</p>';return;}
  const afterPennies=beforePennies-discountPennies,leftPennies=afterPennies-costPennies,perHour=leftPennies/100/hours;
  result.innerHTML=`<div class="stat">Estimate before discount<b>${pounds(beforePennies/100)}</b></div><p>After discount: <b>${pounds(afterPennies/100)}</b></p><p>Job costs: ${pounds(costPennies/100)}<br>Left for your time, tax and overheads: <b>${pounds(leftPennies/100)}</b><br>Return per hour: <b>${pounds(perHour)}</b></p>${afterPennies*4<targetQuarterPennies||afterPennies*4<floorQuarterPennies?'<div class="error" role="alert">This discount takes the quote below your target pay or starting price. Reduce the discount or revise the quote before offering it.</div>':'<div class="notice">This estimate covers the entered costs and your target pay. Check access, wall type, fixings and transport before agreeing it.</div>'}`;
}
const replyTemplates={enquiry:'Hi, thanks for getting in touch with RM Small Jobs. Could you send a photo of what needs doing and let me know which area you are in? I can then assess the job and give you a quote. — Reece',quote:'Hi, the quote for [describe the job] is £[price]. This includes [what is included]. Let me know if you would like to go ahead and we can agree a suitable date and time. — Reece, RM Small Jobs',followup:'Hi, just checking whether you still need help with the job we discussed. Let me know if you have any questions about the quote. — Reece, RM Small Jobs'};
function replyTool(){document.getElementById('toolPanel').innerHTML=`<div class="card"><h2>Prepare a customer reply</h2><div class="field"><label for="reply_type">Choose a reply</label><select id="reply_type" onchange="document.getElementById('reply_text').value=replyTemplates[this.value]"><option value="enquiry">Ask for photos and area</option><option value="quote">Offer a quote</option><option value="followup">Follow up a quote</option></select></div>${textField('reply_text','Message to review',replyTemplates.enquiry,'maxlength="4000"')}<p class="muted">Edit the message to match the actual enquiry. Replace anything in square brackets. WhatsApp will ask you to choose the customer; you still need to press Send.</p><div id="replyError" role="alert"></div><div class="actions"><button class="btn primary" onclick="openReply()">Open WhatsApp draft</button><button class="btn secondary" onclick="copyReply(this)">Copy message</button></div><p class="muted">Only use follow-ups for genuine enquiries. These tools do not send messages or save customer details.</p></div>`;}
function reviewedReply(){requireAuth();const box=document.getElementById('replyError'),text=value('reply_text');box.innerHTML='';if(!text||/\[[^\]]*\]/.test(text)){box.innerHTML=err('Write your message and replace the square-bracket placeholders first.');return null;}return text;}
function openReply(){const text=reviewedReply();if(!text)return;try{window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank','noopener');say('Choose the customer in WhatsApp and press Send. If it did not open, copy the message.');}catch{document.getElementById('replyError').innerHTML=err('WhatsApp could not be opened. Copy the message and paste it into the customer’s chat, then press Send.');}}
async function copyReply(button){const text=reviewedReply();if(!text)return;const input=document.getElementById('reply_text'),box=document.getElementById('replyError'),epoch=authEpoch,visible=()=>epoch===authEpoch&&button.isConnected&&input.isConnected&&box.isConnected;button.disabled=true;try{await navigator.clipboard.writeText(text);if(visible())say('Message copied.');}catch{if(visible()){input.focus();input.select();box.innerHTML=err('Automatic copy is unavailable. Your message is selected: use your device’s Copy option.');}}finally{button.disabled=false;}}
function checklistTool(){const items=['Confirm the job, location and agreed price with the customer','Check wall type, weight, fixings and any hidden cables or pipes where relevant','Confirm you have the tools, skills and materials for this job','Check transport, travel cost and how you will carry everything','Agree access and a suitable date and time','Before leaving: check tools, fixings and phone charge','After the job: confirm completion and record actual costs and payment separately'];document.getElementById('toolPanel').innerHTML=`<div class="card"><h2>Ready for the job?</h2><p class="muted">Use this as a quick prompt. It does not replace a safety assessment or suitable training.</p>${items.map((x,i)=>`<label class="check"><input type="checkbox" onchange="updateChecklist()" id="job_check_${i}"><span>${esc(x)}</span></label>`).join('')}<p id="checklistProgress" role="status">0 of ${items.length} checked</p><p class="muted">Ticks reset when you leave this screen. Keep agreed job details in your private job records.</p></div>`;}
function updateChecklist(){const boxes=[...document.querySelectorAll('#toolPanel input[type="checkbox"]')];document.getElementById('checklistProgress').textContent=boxes.filter(x=>x.checked).length+' of '+boxes.length+' checked';}
