/* Business tools checks use a simulated SDK; no customer contact or live writes. */
const {chromium}=require('playwright');
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
function mockSDK(){
  const session={user:{id:'TEST_ONLY_TOOLS_ACCOUNT'}};
  window.__openCalls=[];window.__copied=[];
  window.open=(...args)=>{window.__openCalls.push(args);return null;};
  Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.__copied.push(text);}}});
  window.supabase={createClient:()=>({auth:{onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),getSession:async()=>({data:{session},error:null})},rpc:async()=>({data:{is_admin:true,schema_version:1},error:null}),from:()=>{const q={select(){return q;},order(){return q;},range(){return q;},then(resolve,reject){return Promise.resolve({data:[],error:null}).then(resolve,reject);}};return q;}})};
}
async function main(){
  const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));try{if(!file.startsWith(root+path.sep))throw new Error('Invalid path');res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':file.endsWith('.webp')?'image/webp':'image/png');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
  try{
    browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
    const base='http://127.0.0.1:'+server.address().port,errors=[],failures=[];
    const context=await browser.newContext({viewport:{width:393,height:852}});
    await context.route('**/*',route=>{const url=route.request().url();if(url.endsWith('/supabase-config.js'))return route.fulfill({contentType:'text/javascript',body:'window.RM_CONFIG={supabaseUrl:"https://test-only.supabase.co",supabaseKey:"sb_publishable_TEST_ONLY_TOOLS_KEY"};'});if(url.startsWith(base))return route.continue();if(url.startsWith('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@'))return route.fulfill({contentType:'text/javascript',body:'('+mockSDK.toString()+')();'});return route.abort();});
    async function page(){const p=await context.newPage();p.on('pageerror',error=>errors.push(error.message));await p.goto(base+'/admin.html');await p.getByRole('heading',{name:'Your business, at a glance',exact:true}).waitFor();await p.getByRole('button',{name:'More',exact:true}).click();return p;}
    async function check(name,run){try{await run();console.log('PASS:',name);}catch(error){failures.push(name+': '+error.message);console.log('FAIL:',name,error.message);}}
    async function costs(p,{rate='1',hours='1',materials='0',travel='0',other='0',discount='0'}={}){for(const [id,text] of Object.entries({quote_rate:rate,quote_hours:hours,quote_materials:materials,quote_travel:travel,quote_other:other,quote_discount:discount}))await p.locator('#'+id).fill(text);}
    await check('All five calculator service floors match built-in customer starting prices',async()=>{const p=await page(),floors=[45,30,30,30,35];assert.deepEqual(await p.locator('#quote_service option').evaluateAll(options=>options.map(x=>Number(x.value))),floors);const publicHTML=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.deepEqual([...publicHTML.matchAll(/<div class="price">From £(\d+)<\/div>/g)].map(x=>Number(x[1])),floors);await costs(p);for(let i=0;i<floors.length;i++){await p.locator('#quote_service').selectOption({index:i});await p.getByRole('button',{name:'Work out quote',exact:true}).click();assert.equal(await p.locator('#quoteResult .stat b').innerText(),'£'+floors[i]+'.00');}});
    await check('Calculator includes time and all costs, rounds to £5, applies discount and recalculates edits',async()=>{const p=await page();await costs(p,{hours:'2',rate:'22.50',materials:'12.35',travel:'4.15',other:'3.50',discount:'5'});await p.getByRole('button',{name:'Work out quote',exact:true}).click();const text=await p.locator('#quoteResult').innerText();assert(text.includes('£65.00'));assert(text.includes('After discount: £60.00'));assert(text.includes('Job costs: £20.00'));assert(text.includes('£40.00'));assert(text.includes('£20.00'));assert(await p.locator('#quoteResult [role=alert]').isVisible());await p.locator('#quote_discount').fill('0');await p.getByRole('button',{name:'Work out quote',exact:true}).click();assert.equal(await p.locator('#quoteResult [role=alert]').count(),0);await p.getByRole('button',{name:'Reply drafts',exact:true}).click();await p.getByRole('button',{name:'Quote calculator',exact:true}).click();assert.equal(await p.locator('#quote_hours').inputValue(),'1');assert.equal(await p.locator('#quote_rate').inputValue(),'');assert.equal(await p.locator('#quoteResult .stat').count(),0);});
    await check('Calculator does not inflate an exact £100 total to £105 through floating-point rounding',async()=>{const p=await page();await costs(p,{materials:'79.93',travel:'11.21',rate:'8.86'});await p.getByRole('button',{name:'Work out quote',exact:true}).click();assert.equal(await p.locator('#quoteResult .stat b').innerText(),'£100.00');});
    await check('Quarter-hour labor retains fractional pennies before rounding, and £0 after discount remains valid',async()=>{const p=await page();await costs(p,{hours:'0.25',rate:'0.01',materials:'45'});await p.getByRole('button',{name:'Work out quote',exact:true}).click();assert.equal(await p.locator('#quoteResult .stat b').innerText(),'£50.00');await costs(p,{discount:'45'});await p.getByRole('button',{name:'Work out quote',exact:true}).click();assert((await p.locator('#quoteResult').innerText()).includes('After discount: £0.00'));assert(await p.locator('#quoteResult [role=alert]').isVisible());});
    await check('Calculator validates missing rate, invalid hours/costs and an excessive discount',async()=>{const p=await page();await p.getByRole('button',{name:'Work out quote',exact:true}).click();assert.equal(await p.locator('#quote_rate').evaluate(x=>x.validity.valueMissing),true);await costs(p,{hours:'0'});await p.getByRole('button',{name:'Work out quote',exact:true}).click();assert.equal(await p.locator('#quote_hours').evaluate(x=>x.validity.rangeUnderflow),true);await costs(p,{hours:'0.3'});assert.equal(await p.locator('#quote_hours').evaluate(x=>x.validity.stepMismatch),true);await costs(p,{materials:'-1'});assert.equal(await p.locator('#quote_materials').evaluate(x=>x.validity.rangeUnderflow),true);await costs(p,{discount:'100'});await p.getByRole('button',{name:'Work out quote',exact:true}).click();assert(await p.locator('.form-error').filter({hasText:'Discount cannot exceed'}).isVisible());assert.equal(await p.locator('#quoteResult .stat').count(),0);});
    await check('Reply selection, edited WhatsApp drafts and blank/placeholders are handled without sending',async()=>{const p=await page();await p.getByRole('button',{name:'Reply drafts',exact:true}).click();assert.match(await p.locator('#reply_text').inputValue(),/photo.*area/);await p.locator('#reply_type').selectOption('quote');assert.match(await p.locator('#reply_text').inputValue(),/\[price\]/);await p.getByRole('button',{name:'Open WhatsApp draft',exact:true}).click();assert.equal(await p.evaluate(()=>__openCalls.length),0);assert(await p.locator('#replyError').filter({hasText:'placeholders'}).isVisible());await p.locator('#reply_text').fill('   ');await p.getByRole('button',{name:'Copy message',exact:true}).click();assert.equal(await p.evaluate(()=>__copied.length),0);await p.locator('#reply_type').selectOption('followup');assert.match(await p.locator('#reply_text').inputValue(),/still need help/);const draft='TEST ONLY: Shelf quote £45 & fixings included.\nPlease confirm.';await p.locator('#reply_text').fill(draft);await p.getByRole('button',{name:'Open WhatsApp draft',exact:true}).click();const args=await p.evaluate(()=>__openCalls[0]);assert.equal(new URL(args[0]).searchParams.get('text'),draft);assert.equal(args[1],'_blank');assert.equal(args[2],'noopener');assert.match(await p.locator('#toast').innerText(),/press Send/);assert.match(await p.locator('#toolPanel').innerText(),/do not send messages/);});
    await check('Copy success and unavailable clipboard select the message for manual copying',async()=>{const p=await page();await p.getByRole('button',{name:'Reply drafts',exact:true}).click();await p.locator('#reply_text').fill('TEST ONLY copied reply');await p.getByRole('button',{name:'Copy message',exact:true}).click();assert.deepEqual(await p.evaluate(()=>__copied),['TEST ONLY copied reply']);assert.match(await p.locator('#toast').innerText(),/Message copied/);await p.evaluate(()=>navigator.clipboard.writeText=async()=>{throw new Error('TEST ONLY copy denied');});await p.getByRole('button',{name:'Copy message',exact:true}).click();assert(await p.locator('#replyError').filter({hasText:'Automatic copy is unavailable'}).isVisible());assert.equal(await p.locator('#reply_text').evaluate(x=>x.selectionEnd-x.selectionStart),22);assert(await p.getByRole('button',{name:'Copy message',exact:true}).isEnabled());});
    await check('Rejected pending copy after leaving Reply drafts causes no error or stale UI changes',async()=>{const p=await page();await p.getByRole('button',{name:'Reply drafts',exact:true}).click();await p.evaluate(()=>navigator.clipboard.writeText=()=>new Promise((resolve,reject)=>window.__rejectCopy=reject));await p.getByRole('button',{name:'Copy message',exact:true}).click();assert(await p.getByRole('button',{name:'Copy message',exact:true}).isDisabled());await p.getByRole('button',{name:'Job checklist',exact:true}).click();const before=errors.length;await p.evaluate(()=>__rejectCopy(new Error('TEST ONLY copy denied')));await p.waitForTimeout(100);assert.equal(errors.length,before);assert(await p.getByRole('heading',{name:'Ready for the job?',exact:true}).isVisible());});
    await check('Successful pending copy after leaving Reply drafts causes no stale toast',async()=>{const p=await page();await p.getByRole('button',{name:'Reply drafts',exact:true}).click();await p.evaluate(()=>navigator.clipboard.writeText=()=>new Promise(resolve=>window.__resolveCopy=resolve));await p.getByRole('button',{name:'Copy message',exact:true}).click();await p.getByRole('button',{name:'Job checklist',exact:true}).click();await p.evaluate(()=>__resolveCopy());await p.waitForTimeout(100);assert.equal(await p.locator('#toast').isVisible(),false);assert(await p.getByRole('heading',{name:'Ready for the job?',exact:true}).isVisible());});
    await check('WhatsApp popup failure gives a copy-message fallback without page error',async()=>{const p=await page();await p.getByRole('button',{name:'Reply drafts',exact:true}).click();await p.evaluate(()=>window.open=()=>{throw new Error('TEST ONLY popup blocked');});const before=errors.length;await p.getByRole('button',{name:'Open WhatsApp draft',exact:true}).click();assert.equal(errors.length,before);assert(await p.locator('#replyError').filter({hasText:'Copy'}).isVisible());});
    await check('Every checklist tick updates progress, unchecking works, and navigation resets ticks',async()=>{const p=await page();await p.getByRole('button',{name:'Job checklist',exact:true}).click();const boxes=p.locator('#toolPanel input[type=checkbox]');assert.equal(await boxes.count(),7);for(let i=0;i<7;i++){await boxes.nth(i).check();assert.equal(await p.locator('#checklistProgress').innerText(),(i+1)+' of 7 checked');}await boxes.nth(0).uncheck();assert.equal(await p.locator('#checklistProgress').innerText(),'6 of 7 checked');await p.getByRole('button',{name:'Quote calculator',exact:true}).click();await p.getByRole('button',{name:'Job checklist',exact:true}).click();assert.equal(await p.locator('#toolPanel input:checked').count(),0);assert.equal(await p.locator('#checklistProgress').innerText(),'0 of 7 checked');});
    await check('All tools tabs fit 320px and 393px mobile viewports',async()=>{const p=await page();for(const width of [320,393]){await p.setViewportSize({width,height:852});for(const tab of ['Quote calculator','Reply drafts','Job checklist']){await p.getByRole('button',{name:tab,exact:true}).click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}}});
    await check('More shortcuts open Leads, Website, password-change URL and safe public configuration download',async()=>{const p=await page();assert.equal(await p.getByRole('link',{name:'Change password',exact:true}).getAttribute('href'),'admin.html?change-password=1');await p.getByRole('button',{name:'Leads & follow-ups',exact:true}).click();await p.getByRole('heading',{name:'Win your first five customers',exact:true}).waitFor();await p.getByRole('button',{name:'More',exact:true}).click();await p.getByRole('button',{name:'Edit website',exact:true}).click();await p.getByRole('heading',{name:'Edit website',exact:true}).waitFor();await p.getByLabel('Headline',{exact:true}).waitFor();await p.getByRole('button',{name:'More',exact:true}).click();const [download]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Public connection file',exact:true}).click()]);assert.equal(download.suggestedFilename(),'supabase-config.js');const stream=await download.createReadStream(),chunks=[];for await(const chunk of stream)chunks.push(chunk);const text=Buffer.concat(chunks).toString();assert(text.includes('https://test-only.supabase.co'));assert(text.includes('sb_publishable_TEST_ONLY_TOOLS_KEY'));assert(!text.includes('TEST_ONLY_TOOLS_ACCOUNT'));});
    await check('No page errors in all simulated tools controls',async()=>assert.deepEqual(errors,[]));
    if(failures.length)throw new Error(failures.join('\n'));
  }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
