/* Browser integration checks use simulated records only; no live Supabase calls. */
const {chromium}=require('playwright');
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=process.env.RM_TEST_OUTPUT||'/tmp/rm-small-jobs-browser-checks';
fs.mkdirSync(out,{recursive:true});
const key='sb_publishable_TEST_ONLY_BROWSER_KEY',project='https://test-only.supabase.co';
const checks=[];function pass(s){checks.push(s);console.log('PASS:',s);}
function mockSDK(){
  const s=window.__mock={admin:window.__admin!==false,signedIn:window.__signedIn!==false,delay:10,fail:null,zero:false,ambiguous:false,reads:[],writes:[],resets:[],passwordUpdates:0,tables:{
    site_settings:[{id:'s1',headline:'Small jobs. Done properly.',intro:'TEST ONLY public intro',boundary:'TEST ONLY price note',phone:'07365 309553',whatsapp:'447365309553',email:'x7reecex@gmail.com',published:false}],
    services:[{id:'s2',name:'TV mounting',price:'From £45',description:'TEST ONLY public service',enabled:true,featured:false,sort_order:0},{id:'s3',name:'HIDDEN TEST SERVICE',price:'£99',enabled:false}],
    faqs:[{id:'f1',question:'TEST ONLY FAQ',answer:'Public answer',enabled:true,sort_order:0}],service_areas:[{id:'a1',name:'Motherwell',enabled:true,sort_order:0}],gallery:[],
    customers:[{id:'c1',name:'TEST ONLY Customer',phone:'07365309553',email:'test-only@example.invalid',address:'TEST ONLY address',postcode:'ML1 1AA',notes:'PRIVATE CUSTOMER NOTE'}],
    jobs:[{id:'j1',title:'TEST ONLY upcoming',status:'Booked',customer_id:'c1',description:'PRIVATE JOB NOTE',location:'PRIVATE LOCATION',price:45,final_price:null,scheduled_at:'2099-10-15T10:00:00Z'},
      {id:'j2',title:'TEST ONLY finished',status:'Completed',price:30,final_price:'50.10'},
      {id:'j3',title:'TEST ONLY no final',status:'Completed',price:900,final_price:null},
      {id:'j4',title:'TEST ONLY free',status:'Completed',price:30,final_price:0},
      {id:'j5',title:'TEST ONLY enquiry',status:'Enquiry',price:999,final_price:null}],
    leads:[],expenses:[{id:'e1',amount:'0.10',category:'Materials',description:'TEST ONLY fixings',expense_date:'2026-10-07'},{id:'e2',amount:'0.20',category:'Other',description:'TEST ONLY packing',expense_date:'2026-10-07'}]
  }};
  let cb;
  window.supabase={createClient:()=>({auth:{
    onAuthStateChange:f=>{cb=f;return {data:{subscription:{unsubscribe(){}}}}},
    getSession:async()=>({data:{session:s.signedIn?{user:{id:'TEST_ONLY_AUTH_USER'}}:null},error:null}),
    signInWithPassword:async()=>{if(s.fail==='auth')return {error:{message:'TEST ONLY invalid credentials'}};s.signedIn=true;const session={user:{id:'TEST_ONLY_AUTH_USER'}};cb('SIGNED_IN',session);return {data:{session},error:null}},
    signOut:async()=>{s.signedIn=false;cb('SIGNED_OUT',null);return {error:null}},
    resetPasswordForEmail:async(email,options)=>{if(s.fail==='reset-network')return {error:{message:'Load failed'}};s.resets.push({email,options});return {data:{},error:null}},
    updateUser:async()=>{s.passwordUpdates++;return {data:{user:{id:'TEST_ONLY_AUTH_USER'}},error:null}}
  },rpc:async name=>name==='rm_admin_status'?s.fail==='rpc'?{error:{message:'TEST ONLY missing setup'}}:{data:{is_admin:s.admin,schema_version:1},error:null}:{error:{message:'Unknown test RPC'}},
  from:table=>{let op='read',data,filter,range;const q={select(){return q},order(){return q},range(a,b){range=[a,b];return q},eq(k,v){filter=[k,v];return q},insert(d){op='insert';data=d;return q},update(d){op='update';data=d;return q},delete(){op='delete';return q},
    then(resolve,reject){return new Promise(r=>setTimeout(r,s.delay)).then(()=>{
      if(op==='read')s.reads.push(table);else s.writes.push({table,op,data:structuredClone(data||{}),filter});
      if(s.fail===table)return {error:{message:'TEST ONLY permission denied'}};
      let rows=s.tables[table]||[];
      if(op==='insert'){
        if(s.zero)return {data:[],error:null};
        if(data.client_request_id&&rows.some(x=>x.client_request_id===data.client_request_id))return {data:null,error:{code:'23505',message:'Duplicate request'}};
        const row={id:'TEST_ONLY_'+s.writes.length,...structuredClone(data)};rows.push(row);
        if(s.ambiguous){s.ambiguous=false;return {data:null,error:{message:'TEST ONLY connection lost after save'}};}
        return {data:[structuredClone(row)],error:null};
      }
      if(filter)rows=rows.filter(x=>String(x[filter[0]])===String(filter[1]));
      if(op==='update'){if(s.zero)return {data:[],error:null};rows.forEach(x=>Object.assign(x,structuredClone(data)));return {data:structuredClone(rows),error:null};}
      if(op==='delete'){if(s.zero)return {data:[],error:null};s.tables[table]=s.tables[table].filter(x=>!rows.includes(x));return {data:structuredClone(rows),error:null};}
      if(range)rows=rows.slice(range[0],range[1]+1);return {data:structuredClone(rows),error:null};
    }).then(resolve,reject)}};return q}
  })};
  window.__recover=()=>cb('PASSWORD_RECOVERY',{user:{id:'TEST_ONLY_AUTH_USER'}});
}
async function main(){
  const server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(req.url.split('?')[0]));try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.html')?'text/html':file.endsWith('.png')?'image/png':'text/plain');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
  const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
  const errors=[],external=[];let admin;
  async function context(options={}){
    const c=await browser.newContext({viewport:{width:393,height:852},acceptDownloads:true,timezoneId:options.timezone||'America/New_York'});
    await c.addInitScript(({key,project,options})=>{window.__signedIn=options.signedIn!==false;window.__admin=options.admin!==false;if(options.connection!==false)localStorage.setItem('rm_sb',JSON.stringify({url:options.storedUrl||project,key}));window.__openCalls=[];window.open=(u)=>{__openCalls.push(u);return null};},{key,project,options});
    await c.route('**/*',async route=>{const u=route.request().url();
      if(u.includes('/supabase-config.js'))return route.fulfill({contentType:'text/javascript',body:'window.RM_CONFIG='+JSON.stringify(options.publicConfig?{supabaseUrl:project,supabaseKey:options.badKey||key,galleryImageHosts:[]}:{})+';'});
      if(u.startsWith(base))return route.continue();
      if(u.includes('cdn.jsdelivr.net/npm/@supabase/supabase-js@2'))return route.fulfill({contentType:'text/javascript',body:'('+mockSDK.toString()+')();'});
      if(u===project+'/rest/v1/rpc/rm_public_site'){
        if(options.failCMS)return route.fulfill({status:503,body:'Unavailable'});
        if(options.badCMS)return route.fulfill({contentType:'application/json',body:JSON.stringify({published:true,settings:{},services:'invalid'})});
        const t=await admin.evaluate(()=>__mock.tables),s=t.site_settings[0];
        const data=s?.published?{published:true,settings:{headline:s.headline,intro:s.intro,boundary:s.boundary,phone:s.phone,whatsapp:s.whatsapp,email:s.email},services:t.services.filter(x=>x.enabled).map(({name,price,description})=>({name,price,description})),faqs:t.faqs.filter(x=>x.enabled).map(({question,answer})=>({question,answer})),areas:t.service_areas.filter(x=>x.enabled).map(({name})=>({name})),gallery:t.gallery.filter(x=>x.published).map(({image_url,title,description})=>({image_url,title,description}))}:{published:false};
        return route.fulfill({contentType:'application/json',body:JSON.stringify(data)});
      }
      if(u===project+'/storage/v1/object/public/work/test.png')return route.fulfill({contentType:'image/png',body:fs.readFileSync(path.join(root,'whatsapp-qr.png'))});
      external.push(u);return route.abort();
    });
    const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));return p;
  }
  try{
    admin=await context();await admin.goto(base+'/admin.html');await admin.getByRole('heading',{name:'Your business, at a glance',exact:true}).waitFor();
    const stats=await admin.locator('.stat').allTextContents();assert(stats.some(x=>x.includes('Completed-job revenue')&&x.includes('£50.10')));assert(stats.some(x=>x.includes('Total expenses')&&x.includes('£0.30')));assert(stats.some(x=>x.includes('Estimated profit')&&x.includes('£49.80')));assert((await admin.locator('body').innerText()).includes('no valid final price'));pass('Dashboard uses completed final prices, zero values and exact pennies; missing prices flagged');
    for(const width of [320,393,768,1440]){await admin.setViewportSize({width,height:852});await admin.evaluate(()=>window.scrollTo(0,0));assert(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Dashboard overflow '+width);if([393,1440].includes(width))await admin.screenshot({path:path.join(out,'dashboard-'+width+'.png'),fullPage:true});}pass('Dashboard layout at 320/393/768/1440 pixels');await admin.setViewportSize({width:393,height:852});
    await admin.getByRole('button',{name:'New customer',exact:true}).click();await admin.getByLabel('Name',{exact:true}).fill('   ');await admin.getByRole('button',{name:'Save customer',exact:true}).click();await admin.locator('.form-error').filter({hasText:'Enter the customer'}).waitFor();assert.equal(await admin.evaluate(()=>__mock.writes.length),0);
    await admin.getByLabel('Name',{exact:true}).fill('TEST ONLY Second Customer');await admin.getByLabel('Phone (optional)',{exact:true}).fill('07700 900123');await admin.getByLabel('Email (optional)',{exact:true}).fill('second-test@example.invalid');await admin.getByLabel('Address (optional)',{exact:true}).fill('TEST ONLY address');await admin.getByLabel('Postcode (optional)',{exact:true}).fill('ml1 1aa');await admin.getByLabel('Notes (optional)',{exact:true}).fill('<img src=x onerror="window.__xss=1">');await admin.getByRole('button',{name:'Save customer',exact:true}).click();await admin.getByRole('heading',{name:'TEST ONLY Second Customer',exact:true}).waitFor();assert.equal(await admin.locator('a').filter({hasText:'WhatsApp'}).getAttribute('href'),'https://wa.me/447700900123');assert.equal(await admin.evaluate(()=>window.__xss),undefined);const customerId=await admin.evaluate(()=>__mock.tables.customers.at(-1).id);pass('Customer creation, contact links and safe notes');
    await admin.getByRole('button',{name:'Edit customer',exact:true}).click();await admin.getByLabel('Name',{exact:true}).fill('TEST ONLY Updated Customer');await admin.getByRole('button',{name:'Save customer',exact:true}).click();await admin.getByRole('heading',{name:'TEST ONLY Updated Customer',exact:true}).waitFor();pass('Customer editing');
    await admin.getByRole('button',{name:'New job for customer',exact:true}).click();await admin.getByLabel('Job title',{exact:true}).fill('TEST ONLY TV fitting');assert.equal(await admin.getByLabel('Customer (optional)',{exact:true}).inputValue(),customerId);await admin.getByRole('button',{name:'Use selected customer’s address',exact:true}).click();assert((await admin.getByLabel('Job address / location',{exact:true}).inputValue()).includes('ML1 1AA'));await admin.getByLabel('Description / notes',{exact:true}).fill('TEST ONLY job description');await admin.getByLabel('Status',{exact:true}).selectOption('Quote sent');await admin.getByLabel('Scheduled date',{exact:true}).fill('2099-10-15');await admin.getByLabel('Scheduled time',{exact:true}).fill('13:30');await admin.getByLabel('Quoted price (£, optional)',{exact:true}).fill('45.50');await admin.evaluate(()=>__mock.delay=200);await admin.getByRole('button',{name:'Save job',exact:true}).click();assert(await admin.getByRole('button',{name:'Save job',exact:true}).isDisabled());await admin.getByRole('heading',{name:'Jobs',exact:true}).waitFor();const job=await admin.evaluate(()=>__mock.tables.jobs.at(-1));assert.equal(job.scheduled_at,'2099-10-15T12:30:00.000Z');assert.equal(job.customer_id,customerId);pass('Full job creation, linked customer, address, London time independent of device timezone and duplicate-tap guard');
    await admin.evaluate(id=>newJob(id),job.id);await admin.getByLabel('Status',{exact:true}).selectOption('Completed');await admin.getByLabel('Final price (£, optional)',{exact:true}).fill('60');await admin.getByRole('button',{name:'Save job',exact:true}).click();await admin.getByRole('heading',{name:'Jobs',exact:true}).waitFor();await admin.evaluate(id=>customerDetail(id),customerId);assert((await admin.locator('body').innerText()).includes('TEST ONLY TV fitting'));await admin.evaluate(()=>home());await admin.getByRole('heading',{name:'Your business, at a glance',exact:true}).waitFor();assert((await admin.locator('.stat').allTextContents()).some(x=>x.includes('revenue')&&x.includes('£110.10')));pass('Completed final price updates revenue and customer history');
    await admin.evaluate(id=>newJob(id),job.id);await admin.getByLabel('Job title',{exact:true}).fill('');admin.once('dialog',d=>d.dismiss());await admin.getByRole('button',{name:'Cancel job',exact:true}).click();assert.equal(await admin.evaluate(id=>__mock.tables.jobs.find(x=>x.id===id).status,job.id),'Completed');admin.once('dialog',d=>d.accept());await admin.getByRole('button',{name:'Cancel job',exact:true}).click();await admin.getByRole('heading',{name:'Jobs',exact:true}).waitFor();assert.equal(await admin.evaluate(id=>__mock.tables.jobs.find(x=>x.id===id).status,job.id),'Cancelled');await admin.evaluate(id=>newJob(id),job.id);admin.once('dialog',d=>d.accept());await admin.getByRole('button',{name:'Delete job',exact:true}).click();await admin.getByRole('heading',{name:'Jobs',exact:true}).waitFor();assert.equal(await admin.evaluate(id=>__mock.tables.jobs.some(x=>x.id===id),job.id),false);pass('Cancel/delete require confirmation and work without validating unsaved fields');
    await admin.evaluate(()=>newExpense());await admin.getByLabel('Amount (£)',{exact:true}).fill('7.25');await admin.getByLabel('Category',{exact:true}).selectOption('Fuel/travel');await admin.getByLabel('Description',{exact:true}).fill('TEST ONLY travel');await admin.getByLabel('Date paid',{exact:true}).fill('2026-10-07');await admin.evaluate(()=>__mock.ambiguous=true);await admin.getByRole('button',{name:'Save expense',exact:true}).click();await admin.locator('.form-error').filter({hasText:'connection lost'}).waitFor();const count=await admin.evaluate(()=>__mock.tables.expenses.length);await admin.getByRole('button',{name:'Save expense',exact:true}).click();await admin.getByRole('heading',{name:'Business money',exact:true}).waitFor();assert.equal(await admin.evaluate(()=>__mock.tables.expenses.length),count);pass('Ambiguous save retry finds original record rather than duplicating expense');
    const expense=await admin.evaluate(()=>__mock.tables.expenses.at(-1));await admin.evaluate(id=>newExpense(id),expense.id);await admin.getByLabel('Amount (£)',{exact:true}).fill('8.50');await admin.evaluate(()=>__mock.zero=true);await admin.getByRole('button',{name:'Save expense',exact:true}).click();await admin.locator('.form-error').filter({hasText:'did not confirm'}).waitFor();assert.equal(await admin.getByLabel('Amount (£)',{exact:true}).inputValue(),'8.50');await admin.evaluate(()=>__mock.zero=false);await admin.getByRole('button',{name:'Save expense',exact:true}).click();await admin.getByRole('heading',{name:'Business money',exact:true}).waitFor();await admin.evaluate(id=>newExpense(id),expense.id);await admin.getByLabel('Date paid',{exact:true}).fill('');admin.once('dialog',d=>d.dismiss());await admin.getByRole('button',{name:'Delete expense',exact:true}).click();assert(await admin.getByRole('button',{name:'Delete expense',exact:true}).isVisible());admin.once('dialog',d=>d.accept());await admin.getByRole('button',{name:'Delete expense',exact:true}).click();await admin.getByRole('heading',{name:'Business money',exact:true}).waitFor();pass('Expense editing, no-confirmation failure retention and confirmed deletion');
    const fallback=await context({connection:false});await fallback.goto(base);assert.equal((await fallback.evaluate(()=>rmCmsReady)).reason,'not-configured');assert.deepEqual(await fallback.locator('.card .price').allTextContents(),['From £45','From £30','From £30','From £30','From £35','Quote']);assert(await fallback.locator('.qr').isVisible());assert.match(await fallback.locator('.launch-offer').innerText(),/£10 off your first job over £40/);pass('Unconfigured public site preserves current pricing, layout and QR');
    await fallback.locator('#cmsServices a[data-service="TV mounting"]').focus();await fallback.keyboard.press('Enter');assert(await fallback.locator('#quoteServiceHint').isVisible());assert.match(await fallback.locator('#quoteServiceHint').innerText(),/TV mounting/);assert.equal(await fallback.evaluate(()=>document.activeElement.id),'qArea');await fallback.locator('#qArea').fill('TEST ONLY ML1');await fallback.locator('#qJob').fill('TEST ONLY 43 inch TV & bracket');await fallback.locator('#quoteForm button[type=submit]').click();let draft=new URL(await fallback.evaluate(()=>__openCalls.at(-1))).searchParams.get('text');assert.match(draft,/Service: TV mounting/);assert.match(draft,/Job: TEST ONLY 43 inch TV & bracket/);await fallback.locator('#cmsServices a[data-service="Furniture assembly"]').click();assert(await fallback.locator('#quoteForm').isVisible());assert(await fallback.locator('#quoteFollowUp').isHidden());assert.equal(await fallback.locator('#qJob').inputValue(),'TEST ONLY 43 inch TV & bracket');assert.equal(await fallback.evaluate(()=>__openCalls.length),1);await fallback.getByRole('button',{name:'Clear service choice',exact:true}).click();await fallback.locator('#quoteForm button[type=submit]').click();draft=new URL(await fallback.evaluate(()=>__openCalls.at(-1))).searchParams.get('text');assert(!draft.includes('Service:'));for(const width of [320,393,768,1440]){await fallback.setViewportSize({width,height:852});assert(await fallback.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Service cards overflow '+width);}assert.equal(await fallback.locator('link[rel=canonical]').getAttribute('href'),'https://www.rmsmalljobs.co.uk/');assert.equal(await fallback.locator('meta[property="og:image"]').getAttribute('content'),'https://www.rmsmalljobs.co.uk/logo.png');await fallback.setViewportSize({width:393,height:852});await fallback.locator('#services').scrollIntoViewIfNeeded();await fallback.screenshot({path:path.join(out,'service-quote-mobile.png')});pass('Keyboard service selection enters WhatsApp draft; changing/clearing keeps details and never sends automatically; all viewport sizes');
    const publicPage=await context({publicConfig:true,connection:false});await publicPage.goto(base);assert.equal((await publicPage.evaluate(()=>rmCmsReady)).reason,'not-published');pass('CMS publication gate keeps unchecked drafts off public site');
    await admin.evaluate(()=>website());await admin.getByLabel('Headline',{exact:true}).waitFor();await admin.getByLabel('Headline',{exact:true}).fill('TEST ONLY published headline');await admin.getByLabel('Introduction',{exact:true}).fill('<script>window.__xss=2</script>');await admin.getByLabel('Publish the CMS content on the public website',{exact:true}).check();admin.once('dialog',d=>d.accept());await admin.getByRole('button',{name:'Save homepage',exact:true}).click();await admin.getByLabel('Headline',{exact:true}).waitFor();await admin.waitForFunction(()=>__mock.tables.site_settings[0].published===true&&document.querySelector('#headline')?.value==='TEST ONLY published headline'&&document.querySelector('button[type=submit]')?.disabled===false);await publicPage.reload();assert.equal((await publicPage.evaluate(()=>rmCmsReady)).status,'published');assert.equal(await publicPage.locator('h1').innerText(),'TEST ONLY published headline');assert.equal(await publicPage.locator('#cmsServices .card').count(),1);assert.equal(await publicPage.evaluate(()=>window.__xss),undefined);assert(await publicPage.locator('#faqs').isVisible());assert(!(await publicPage.locator('body').innerText()).includes('PRIVATE CUSTOMER NOTE'));pass('Admin homepage publication reaches public page; enabled-only CMS and safe text');
    for(const tab of ['services','faq','areas','gallery']){await admin.evaluate(t=>renderWeb(t),tab);await admin.evaluate(t=>recordForm(t,-1),tab);if(tab==='services'){await admin.getByLabel('Service name',{exact:true}).fill('TEST ONLY added service');await admin.getByLabel('Starting price',{exact:true}).fill('From £35');await admin.getByLabel('Description',{exact:true}).fill('TEST ONLY service detail');}if(tab==='faq'){await admin.getByLabel('Question',{exact:true}).fill('TEST ONLY added FAQ');await admin.getByLabel('Answer',{exact:true}).fill('TEST ONLY answer');}if(tab==='areas')await admin.getByLabel('Area name',{exact:true}).fill('Wishaw');if(tab==='gallery'){await admin.getByLabel('Photo URL',{exact:true}).fill('https://test-only.supabase.co/storage/v1/object/public/work/test.png');await admin.getByLabel('Photo title',{exact:true}).fill('TEST ONLY photo');await admin.getByLabel('Photo description',{exact:true}).fill('TEST ONLY caption');}await admin.getByLabel('Show on the published website',{exact:true}).check();await admin.getByRole('button',{name:'Save item',exact:true}).click();await admin.getByRole('heading',{name:'Edit website',exact:true}).waitFor();await admin.waitForFunction(()=>document.querySelector('#panel')&&!document.querySelector('#panel form'));}await publicPage.reload();await publicPage.evaluate(()=>rmCmsReady);assert.equal(await publicPage.locator('#cmsServices .card').count(),2);assert((await publicPage.locator('#cmsAreas').innerText()).includes('Wishaw'));assert.equal(await publicPage.locator('#cmsFaqs details').count(),2);assert.equal(await publicPage.locator('#cmsGallery figure').count(),1);pass('All CMS collections save through admin and render publicly');await publicPage.locator('#cmsServices a').filter({hasText:'TEST ONLY added service'}).click();assert.match(await publicPage.locator('#quoteServiceHint').innerText(),/TEST ONLY added service/);await publicPage.locator('#qArea').fill('TEST ONLY ML1');await publicPage.locator('#qJob').fill('TEST ONLY published service details');await publicPage.locator('#quoteForm button[type=submit]').click();assert.match(new URL(await publicPage.evaluate(()=>__openCalls.at(-1))).searchParams.get('text'),/Service: TEST ONLY added service/);pass('Published CMS service cards use the same quote route');for(const width of [320,393,768,1440]){await publicPage.setViewportSize({width,height:852});assert(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'CMS public layout overflow '+width);}pass('Published CMS public layout at 320/393/768/1440 pixels');
    await admin.evaluate(()=>{__mock.tables.services.forEach(x=>x.enabled=false);__mock.tables.faqs.forEach(x=>x.enabled=false);__mock.tables.service_areas.forEach(x=>x.enabled=false);__mock.tables.gallery=[];});await publicPage.reload();await publicPage.evaluate(()=>rmCmsReady);assert.equal(await publicPage.locator('#cmsServices .card').count(),0);assert(await publicPage.locator('#faqs').isHidden());assert(!(await publicPage.locator('#cmsAreas').innerText()).includes('Motherwell'));pass('Successful empty public collections do not resurrect disabled fallback records');
    const failed=await context({publicConfig:true,connection:false,failCMS:true});await failed.goto(base);assert.equal((await failed.evaluate(()=>rmCmsReady)).status,'fallback');assert.equal(await failed.locator('.card .price').count(),6);const malformed=await context({publicConfig:true,connection:false,badCMS:true});await malformed.goto(base);assert.equal((await malformed.evaluate(()=>rmCmsReady)).status,'fallback');pass('Unavailable/malformed CMS leaves the complete fallback website working');
    await admin.evaluate(()=>{__mock.tables.site_settings[0].whatsapp='447700900123';});await publicPage.reload();await publicPage.evaluate(()=>rmCmsReady);assert(await publicPage.locator('.qr').isHidden());await publicPage.locator('#qArea').fill('TEST ONLY ML1');await publicPage.locator('#qJob').fill('TEST ONLY quote');await publicPage.locator('#quoteForm button[type=submit]').click();assert((await publicPage.evaluate(()=>__openCalls.at(-1))).startsWith('https://wa.me/447700900123?'));assert(await publicPage.locator('#quoteFollowUp').isVisible());assert((await publicPage.locator('#quoteFollowUp').innerText()).includes('isn’t a booking'));await publicPage.goto(base+'/thank-you/?success=true');await publicPage.evaluate(()=>rmCmsReady);assert((await publicPage.locator('body').innerText()).includes('can’t confirm'));pass('CMS WhatsApp destination, honest QR mismatch handling, quote flow and next steps');
    await admin.evaluate(()=>home());await admin.getByRole('button',{name:'Export business records',exact:true}).waitFor();const [download]=await Promise.all([admin.waitForEvent('download'),admin.getByRole('button',{name:'Export business records',exact:true}).click()]);const stream=await download.createReadStream();let chunks=[];for await(const chunk of stream)chunks.push(chunk);const text=Buffer.concat(chunks).toString();assert.equal(Object.keys(JSON.parse(text).tables).length,8);assert(!text.includes(key));assert(!text.includes('TEST_ONLY_AUTH_USER'));pass('Authenticated private export contains business tables without keys or auth tokens');
    await admin.evaluate(()=>__mock.fail='jobs');await admin.evaluate(()=>home());await admin.getByRole('alert').filter({hasText:'permission denied'}).waitFor();assert.equal(await admin.locator('.stat').count(),0);await admin.evaluate(()=>__mock.fail=null);await admin.getByRole('button',{name:'Try again',exact:true}).click();await admin.getByRole('heading',{name:'Your business, at a glance',exact:true}).waitFor();pass('Failed reads never produce misleading empty totals');
    await admin.getByRole('button',{name:'Log out',exact:true}).click();await admin.getByRole('heading',{name:'Sign in',exact:true}).waitFor();assert.equal(await admin.locator('.nav').count(),0);assert.equal(await admin.evaluate(()=>jobRows.length+expenseRows.length+customerRows.length),0);await admin.getByLabel('Email',{exact:true}).fill('test-only@example.invalid');await admin.getByLabel('Password',{exact:true}).fill('TEST_ONLY_password');await admin.evaluate(()=>__mock.fail='auth');await admin.getByRole('button',{name:'Sign in',exact:true}).click();await admin.locator('.form-error').filter({hasText:'invalid credentials'}).waitFor();await admin.evaluate(()=>__mock.fail=null);await admin.getByRole('button',{name:'Sign in',exact:true}).click();await admin.getByRole('heading',{name:'Your business, at a glance',exact:true}).waitFor();await admin.getByRole('button',{name:'Log out',exact:true}).click();await admin.getByRole('heading',{name:'Sign in',exact:true}).waitFor();pass('Sign-in error preserves fields; successful retry verifies admin access');await admin.getByRole('button',{name:'Forgot password?',exact:true}).click();await admin.getByLabel('Account email',{exact:true}).fill('test-only@example.invalid');await admin.getByRole('button',{name:'Email reset link',exact:true}).click();await admin.getByRole('heading',{name:'Check your email',exact:true}).waitFor();assert.equal(await admin.evaluate(()=>__mock.resets[0].options.redirectTo),base+'/admin.html');await admin.evaluate(()=>__recover());await admin.getByLabel('New password',{exact:true}).fill('TEST_ONLY_password');await admin.getByLabel('Confirm password',{exact:true}).fill('different_password');await admin.getByRole('button',{name:'Save new password',exact:true}).click();await admin.locator('.form-error').filter({hasText:'do not match'}).waitFor();await admin.getByLabel('Confirm password',{exact:true}).fill('TEST_ONLY_password');await admin.getByRole('button',{name:'Save new password',exact:true}).click();await admin.getByRole('heading',{name:'Your business, at a glance',exact:true}).waitFor();pass('Logout clears private cache; password reset request/recovery validates matching passwords');
    await admin.getByRole('button',{name:'Leads & follow-ups',exact:true}).click();await admin.getByRole('heading',{name:'Win your first five customers',exact:true}).waitFor();await admin.getByRole('button',{name:'New opportunity',exact:true}).click();await admin.getByLabel('Work needed',{exact:true}).fill('<img src=x onerror="window.__leadXss=1"> TEST ONLY assembly');await admin.getByLabel('Town / postcode',{exact:true}).fill('TEST ONLY ML1');await admin.getByLabel('Public source link',{exact:true}).fill('https://example.invalid/public-request');await admin.getByLabel('Request date as shown',{exact:true}).fill('29 Sept; year not shown');await admin.getByLabel('Follow-up date',{exact:true}).fill('2026-01-01');await admin.getByLabel('Quote (£, optional)',{exact:true}).fill('999');await admin.getByRole('button',{name:'Save opportunity',exact:true}).click();await admin.getByRole('heading',{name:'Win your first five customers',exact:true}).waitFor();assert((await admin.locator('.stat').allTextContents()).some(x=>x.includes('Payments recorded')&&x.includes('£0.00')));assert.equal(await admin.evaluate(()=>window.__leadXss),undefined);await admin.getByLabel('Show opportunities',{exact:true}).selectOption('due');assert.equal(await admin.getByRole('button',{name:'Open opportunity',exact:true}).count(),1);pass('Private lead creation, escaped content, due follow-ups and quotes excluded from cash receipts');
    await admin.getByRole('button',{name:'Open opportunity',exact:true}).click();await admin.getByLabel('Total payment received (£)',{exact:true}).fill('35');await admin.getByRole('button',{name:'Save opportunity',exact:true}).click();await admin.locator('.form-error').filter({hasText:'customer reference'}).waitFor();await admin.getByLabel('Customer reference',{exact:true}).fill('TEST-CUSTOMER');await admin.getByLabel('Link existing job (optional)',{exact:true}).selectOption('j2');await admin.getByRole('button',{name:'Save opportunity',exact:true}).click();await admin.getByRole('heading',{name:'Win your first five customers',exact:true}).waitFor();assert((await admin.locator('.stat').allTextContents()).some(x=>x.includes('Completed paying customers')&&x.includes('1 / 5')));await admin.evaluate(()=>{const one=__mock.tables.leads[0];__mock.tables.leads.push({...one,id:'TEST_SECOND_LEAD',job_id:null,status:'Completed',received_amount:10,customer_ref:'test-customer'});});await admin.evaluate(()=>leads());await admin.getByRole('heading',{name:'Win your first five customers',exact:true}).waitFor();const totals=await admin.evaluate(()=>leadTotals(leadRows));assert.equal(totals.paying,1);assert.equal(totals.receipts,4500);assert.equal(totals.completed,4);assert.equal(totals.booked,1);pass('Recorded receipts require customer reference; repeated customers and linked completed jobs count once');
    for(const width of [320,393,768,1440]){await admin.setViewportSize({width,height:852});assert(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Lead board overflow '+width);}await admin.setViewportSize({width:393,height:852});await admin.screenshot({path:path.join(out,'lead-dashboard-mobile.png'),fullPage:true});await admin.evaluate(()=>__mock.fail='leads');await admin.evaluate(()=>leads());await admin.getByRole('alert').filter({hasText:'permission denied'}).waitFor();assert.equal(await admin.locator('.stat').count(),0);await admin.evaluate(()=>__mock.fail=null);await admin.evaluate(()=>leads());await admin.getByRole('heading',{name:'Win your first five customers',exact:true}).waitFor();await admin.getByRole('button',{name:'Log out',exact:true}).click();await admin.getByRole('heading',{name:'Sign in',exact:true}).waitFor();assert.equal(await admin.evaluate(()=>leadRows.length),0);await admin.getByLabel('Email',{exact:true}).fill('test-only@example.invalid');await admin.getByLabel('Password',{exact:true}).fill('TEST_ONLY_password');await admin.getByRole('button',{name:'Sign in',exact:true}).click();await admin.getByRole('heading',{name:'Your business, at a glance',exact:true}).waitFor();pass('Lead mobile layouts, unavailable schema/read errors, logout privacy and no automatic outreach');
    const stranger=await context({admin:false});await stranger.goto(base+'/admin.html');await stranger.getByRole('heading',{name:'Admin access is not enabled',exact:true}).waitFor();assert.equal(await stranger.evaluate(()=>__mock.reads.length),0);const signedOut=await context({signedIn:false});await signedOut.goto(base+'/admin.html');await signedOut.getByRole('heading',{name:'Sign in',exact:true}).waitFor();assert.equal(await signedOut.evaluate(()=>__mock.reads.length),0);pass('Signed-out and unapproved accounts never load private records');
    const resume=await context();await resume.goto(base+'/admin.html?change-password=1');await resume.getByRole('heading',{name:'Set a new password',exact:true}).waitFor();assert.equal(await resume.evaluate(()=>__mock.reads.length),0);assert.equal(await resume.evaluate(()=>__mock.resets.length),0);await resume.getByLabel('New password',{exact:true}).fill('TEST_ONLY_password');await resume.getByLabel('Confirm password',{exact:true}).fill('TEST_ONLY_password');await resume.getByRole('button',{name:'Save new password',exact:true}).click();await resume.getByRole('heading',{name:'Your business, at a glance',exact:true}).waitFor();assert.equal(await resume.evaluate(()=>__mock.passwordUpdates),1);assert.equal(new URL(resume.url()).search,'');pass('Existing approved session can save a new password without another email or early private reads');
    for(const options of [{signedIn:false},{admin:false}]){const denied=await context(options);await denied.goto(base+'/admin.html?change-password=1');await denied.getByRole('heading',{name:options.signedIn===false?'Sign in':'Admin access is not enabled',exact:true}).waitFor();assert.equal(await denied.getByLabel('New password',{exact:true}).count(),0);assert.equal(await denied.evaluate(()=>__mock.passwordUpdates+__mock.reads.length+__mock.resets.length),0);}pass('Password-change URL requires an authenticated approved owner');
    const stale=await context({signedIn:false,publicConfig:true,storedUrl:'https://metaquqdynxwkplojlhwq.supabase.co/'});await stale.goto(base+'/admin.html');await stale.getByRole('heading',{name:'Sign in',exact:true}).waitFor();assert.equal(await stale.evaluate(()=>cfg.url),project);assert.equal(await stale.evaluate(()=>JSON.parse(localStorage.getItem('rm_sb')).url),project);assert.equal(await stale.evaluate(()=>__mock.reads.length),0);pass('Saved legacy project-address typo repairs to the configured website connection');
    const repair=await context({signedIn:false,publicConfig:true,storedUrl:'https://old-connection.example.invalid'});await repair.goto(base+'/admin.html');await repair.getByRole('heading',{name:'Sign in',exact:true}).waitFor();assert.equal(await repair.evaluate(()=>cfg.url),'https://old-connection.example.invalid');await repair.getByRole('button',{name:'Forgot password?',exact:true}).click();await repair.getByLabel('Account email',{exact:true}).fill('test-only@example.invalid');await repair.evaluate(()=>__mock.fail='reset-network');await repair.getByRole('button',{name:'Email reset link',exact:true}).click();await repair.getByRole('button',{name:'Use website connection',exact:true}).waitFor();assert.match(await repair.locator('.form-error').innerText(),/Safari or Chrome/);await repair.getByRole('button',{name:'Use website connection',exact:true}).click();await repair.getByRole('heading',{name:'Reset your password',exact:true}).waitFor();assert.equal(await repair.getByLabel('Account email',{exact:true}).inputValue(),'test-only@example.invalid');assert.equal(await repair.evaluate(()=>cfg.url),project);assert.equal(await repair.evaluate(()=>__mock.resets.length),0);assert.equal(await repair.evaluate(()=>__mock.reads.length),0);await repair.evaluate(()=>__mock.fail=null);await repair.getByRole('button',{name:'Email reset link',exact:true}).click();await repair.getByRole('heading',{name:'Check your email',exact:true}).waitFor();assert.equal(await repair.evaluate(()=>__mock.resets.length),1);pass('Reset network errors explain browser recovery; explicit connection repair keeps email and sends no reset until retry');
    const bad=await context({connection:false,publicConfig:true,badKey:'sb_secret_TEST_ONLY_SECRET'});await bad.goto(base);assert.equal((await bad.evaluate(()=>rmCmsReady)).reason,'invalid-configuration');await bad.goto(base+'/admin.html');await bad.getByRole('heading',{name:'Connect your business app',exact:true}).waitFor();assert.equal(await bad.evaluate(()=>__mock.reads.length),0);pass('Secret key rejected before any database request');
    const helper=await admin.evaluate(()=>{const d=[];for(const [date,time] of [['2026-03-29','01:30'],['2026-10-25','01:30']]){try{londonTimestamp(date,time);d.push(false)}catch{d.push(true)}}return {dst:d,summer:londonTimestamp('2026-07-15','13:30'),winter:londonTimestamp('2026-12-15','13:30')};});assert.deepEqual(helper.dst,[true,true]);assert.equal(helper.summer,'2026-07-15T12:30:00.000Z');assert.equal(helper.winter,'2026-12-15T13:30:00.000Z');pass('London summer/winter scheduling and both clock-change edge cases');
    assert.deepEqual(errors,[]);assert.deepEqual(external.filter(u=>!u.includes('/storage/v1/object/public/work/test.png')),[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checked_at:new Date().toISOString(),checks,real_supabase_requests:0,errors},null,2));console.log('PASS:',checks.length,'browser scenarios; no real Supabase requests');
  }finally{await browser.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e);process.exit(1)});
